# mypy: ignore-errors
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aortica.api import ecg_service_pb2 as ecg__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ecg_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ECGPredictionServiceStub(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    ECGPredictionService provides single and batch ECG inference.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/aortica.ECGPredictionService/Predict',
                request_serializer=ecg__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=ecg__service__pb2.PredictReply.FromString,
                _registered_method=True)
        self.PredictBatch = channel.unary_unary(
                '/aortica.ECGPredictionService/PredictBatch',
                request_serializer=ecg__service__pb2.PredictBatchRequest.SerializeToString,
                response_deserializer=ecg__service__pb2.PredictBatchReply.FromString,
                _registered_method=True)


class ECGPredictionServiceServicer(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    ECGPredictionService provides single and batch ECG inference.
    """

    def Predict(self, request, context):
        """Process a single ECG file and return multi-task predictions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBatch(self, request, context):
        """Process multiple ECG files in a single call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ECGPredictionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ecg__service__pb2.PredictRequest.FromString,
                    response_serializer=ecg__service__pb2.PredictReply.SerializeToString,
            ),
            'PredictBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBatch,
                    request_deserializer=ecg__service__pb2.PredictBatchRequest.FromString,
                    response_serializer=ecg__service__pb2.PredictBatchReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aortica.ECGPredictionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aortica.ECGPredictionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ECGPredictionService(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    ECGPredictionService provides single and batch ECG inference.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aortica.ECGPredictionService/Predict',
            ecg__service__pb2.PredictRequest.SerializeToString,
            ecg__service__pb2.PredictReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aortica.ECGPredictionService/PredictBatch',
            ecg__service__pb2.PredictBatchRequest.SerializeToString,
            ecg__service__pb2.PredictBatchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
